### ISSUE TITLE
Nullable related refactors may be required after migration to null-safety

### ISSUE THREAD

**Issue by bryancalisto** [shadabunique/flutter_draggable_fab#5]
Hi! Nice package! 

I just wantent to mention 2 things I noticed:

1. Is there a reason why "child" field  should be nullable in "DraggableFab" class ? I couldn't figure out a use case where "child" should be null. It could be converted to non-nullable and required to take advantage of null-safety.
2. The example project could not be built (build error) because of null-safety related errors caused by flutter "sdk" field in pubspec.yaml (">=2.1.0 <3.0.0"). If changed to ">=2.12.0 <3.0.0", it works.

Can I submit a pull request to refactor/fix these issues?

**Comment by shadabunique** [comment]
Sure. Please go ahead.

**Comment by shadabunique** [comment]
Fixed
